# NumPy (Numerical Python)

NumPy works on **multidimensional homogeneous array objects** and it provides a collection of functions to process those arrays. NumPy is known for the fast numerical computations. Numpy provides a high level syntax and it has a very vibrant ecosystem that interopertes for different application areas. The n-dimensional arrays are known as **ndarray**. ndarray forms the primitive building blocks of numerous python libraries.

# Importing numpy

NumPy is available by default in Colab notebooks. Therefore the library can be invoked directly using the *import* statement

*PS: Follow the instructions on the [Installation section](https://numpy.org/install/) of NumPy to make local installations.*


In [30]:
import numpy as np
print("Loaded", np.__version__, "version of numpy!!!")

Loaded 1.26.4 version of numpy!!!


# Creating NumPy arrays

The basic ndarray is created using the **array** function, which takes any sequence as an input parameter. NumPy arrays can be easily created from lists 


In [31]:
# creating a 1 dimensional array
var1 = np.array([1, 2, 3, 4, 5])

# creating a 2 dimensional array
var2 = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 0]])

print("var1 =", var1)
print("var2 =", var2)

var1 = [1 2 3 4 5]
var2 = [[1 2 3 4 5]
 [6 7 8 9 0]]


In [32]:
# It is also possible to specify the type of the element during array creation
var3 = np.array([1, 2, 3], dtype=np.float32)
print("var3 =", var3)

# Notice the usage of numpy arrays to create another array with a different dtype
var4 = np.array(var3, dtype=np.int32)
print("var4 =", var4)

var5 = np.array(var4, dtype=complex)
print("var5 =", var5)

var3 = [1. 2. 3.]
var4 = [1 2 3]
var5 = [1.+0.j 2.+0.j 3.+0.j]


# Array Properties
The important attributes of the ndarray are

*   shape: Dimensions of the array
*   size: Total number of elements in the array
*   ndim: Number of axes
*   dtype: Type of the elements of the array



In [33]:
print('type', '\t', 'shape', '\t', 'size', '\t', 'dimentions')

print(var1.dtype, '\t', var1.shape, '\t', var1.size, '\t', var1.ndim)
print(var2.dtype, '\t', var2.shape, '\t', var2.size, '\t', var2.ndim)
print(var3.dtype, '\t', var3.shape, '\t', var3.size, '\t', var3.ndim)
print(var4.dtype, '\t', var4.shape, '\t', var4.size, '\t', var4.ndim)
print(var5.dtype, '\t', var5.shape, '\t', var5.size, '\t', var5.ndim)

type 	 shape 	 size 	 dimentions
int64 	 (5,) 	 5 	 1
int64 	 (2, 5) 	 10 	 2
float32 	 (3,) 	 3 	 1
int32 	 (3,) 	 3 	 1
complex128 	 (3,) 	 3 	 1


# Other array creation methods

It is not always necessary to have the elements defined during the creation of the arrays. There are several NumPy functions that allows you to create arrays to act as placeholders before the actual computations.

**Exercise #01:**

*   Create different array objects using the following functions: (1) zeros, (2) ones, (3) empty, (4) zeros_like, (5) ones_like, (6) empty_like 


In [39]:
# Solution
# np.zeros((2, 5, 10))
arr1 = np.zeros((2,2,4), dtype=float)
print(arr1)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [35]:
# Solution
# np.zeros((2, 5, 10))
arr2 = np.ones((2,2))
print(arr2)

[[1. 1.]
 [1. 1.]]


In [38]:
arr3 = np.empty((3,2))
print(arr3) # why are they cero with float??

[[1. 0.]
 [2. 0.]
 [3. 0.]]


In [46]:
arr4 = np.zeros_like(arr1) # i have to tell it to be like another array but I cannot tell it to be like a created array? yes, I can, I had a mistake in 'zero' instead of 'zeros'
print(arr4)  # Can 

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [45]:
a = np.array([[1, 2], [3, 4]])
arr4 = np.zeros_like(a)
print(arr4)  # Can 

[[0 0]
 [0 0]]


In [48]:
# ones_like
arr5 = np.ones_like(a)
print(arr5)


[[1 1]
 [1 1]]


In [49]:
# (6) empty_like 
arr6 = np.empty_like(a)
print(arr6) 

[[1 1]
 [1 1]]


**Exercise #02:**

*   What is the difference between **empty** and **zeros** methods?
*   What is the use of **arange** and **linspace** functions?



**Solution**

1- `zero` creates an array of a specified shape and type with **ZEROS**. `Empty` creates an array of a specified shape and type without initializing its entries. This means the array could have random values, as they are whatever was already located in memory.

2- a) **arange** works similar to `range` in a list or other types normaly used in python: takes three arguments: `start`, `stop`, and `step`

b) **linspace** is used to create an array of evenly spaced numbers over a specified interval.

Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
*	start: The starting value of the sequence.
* stop: The end value of the sequence.
* num: The number of evenly spaced samples to generate (default is 50).
* endpoint: If True (default), stop is the last sample. If False, it is not included, and it extends just up to it.
* retstep: If True, it returns (samples, step), where step is the spacing between samples.
* dtype: The type of the output array.
* axis: The axis in the result to store the samples (relevant for multi-dimensional arrays).

...



# Shape Manipulations

In [52]:
# Creating a numpy array using arrange function
var6 = np.arange(10, dtype=int)
print(var6, "\n")

# Reshaping the array into 2 x 5 array
var6 = var6.reshape(2,5)
print(var6, "\n")

# Reshaping the array in 3 dimensions
var6 = var6.reshape(1,2,5)
print(var6, "\n")

# Note that it is not always necessary to give all three dimensions
var6 = var6.reshape(1,2,-1)
print(var6, "\n")

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 



**Exercise #03:**

*   What is the difference between reshape and resize methods?



**Solution**

`reshape`

* Purpose: Returns a new array with the same data but a different shape.

* Behavior: The total number of elements remains unchanged. The function is non-destructive—meaning it doesn't alter the original array if the new shape is compatible. Instead, it returns a reshaped view of the original data.

* Usage: reshape is used when you want to temporarily work with a view of the array in a different shape without affecting the original data.

* Syntax: array.reshape(new_shape)

`resize`

* Purpose: Alters the size and shape of the array in place.
* Behavior: If the new shape has more elements than the initial array, resize will fill the new values with zero (or default value). If the new shape has fewer elements, the array will be trimmed. This operation modifies the original array's data.

* Usage: resize is used when you want to permanently change the array size and shape, effectively adjusting the data within.

* Syntax: array.resize(new_shape)

**Key Differences**

* Mutation: reshape returns a new view, leaving the original array unchanged, while resize modifies the original array in place.
* Element Count: reshape requires that the total number of elements remain constant, whereas resize can either truncate or pad the array, changing the total number of elements.
* Impact: Use reshape for temporary viewing and manipulation, and resize when you need to actually alter the array size/shape for further use.


...

# Indexing, Slicing and Iterating

Indexing and slicing is similar to python lists. We use the **[ ]** operator for providing slices and indices.

In [53]:
var7 = np.array([1, 2, 3, 4, 5])

# indexing the second element
# Remember array indices start with 0 in numpy
print(var7[1])

# slicing the first two elements of the array
print(var7[0:2])

2
[1 2]


In [54]:
# it is also possible to slice arrays based on a condition
print(var7[var7 % 2 == 0])  # prints all the even numbers in the array

[2 4]


In [57]:
var8 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(var8, "\n")

# indexing the element at second row and second column
print(var8[1,1], "\n")

# it is possible to slice the entire row or column
print(var8[1])
print(var8[:,1], "\n")

# slice a particular range
print(var8[0:2, 0:2], "\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

5 

[4 5 6]
[2 5 8] 

[[1 2]
 [4 5]] 



A visual illustration of slicing mechanism can be seen here

![numpy_indexing.png](https://education-team-2020.s3.eu-west-1.amazonaws.com/ds-ai/indexing-and-slicing.png)

*Reference: https://lectures.scientific-python.org/intro/numpy/array_object.html#indexing-and-slicing*

# **Exercise #04:**

*   What is the use of non-zero function? Provide an example of how non-zero function can be used.



**Solution**

`numpy.nonzero()` function is a tool used to find the indices/index of non-zero elements in an array.

* Purpose: Returns a tuple of arrays, one for each dimension of the input array, containing the indices of the non-zero elements.



...

In [61]:
# solution

import numpy as np

# Create a sample array
array = np.array([[1, 0, 3], 
                  [0, 4, 0], 
                  [5, 6, 0]])

# Use nonzero() to find indices of non-zero elements
non_zero_indices = np.nonzero(array)

print("Non-zero indices in each dimension:")
print(non_zero_indices)

# Extracting non-zero elements using these indices
non_zero_elements = array[non_zero_indices]
print("Non-zero elements:")
print(non_zero_elements)

Non-zero indices in each dimension:
(array([0, 0, 1, 2, 2]), array([0, 2, 1, 0, 1]))
Non-zero elements:
[1 3 4 5 6]


***Step-by-step Execution of np.nonzero(array):***

1. Find Non-zero Elements: np.nonzero() scans each element of the array to determine which are non-zero. The goal is to figure out the position of each non-zero element.

2. Resulting Indices:

*	The function returns two arrays (since it's a 2D array), where:
*	The first array gives the row indices of non-zero elements.
*	The second array gives the column indices corresponding to those row indices.

3. Extract Indices:

*	array[0, 0] = 1 (Non-zero)
*	array[0, 2] = 3 (Non-zero)
*	array[1, 1] = 4 (Non-zero)
*	array[2, 0] = 5 (Non-zero)
*	array[2, 1] = 6 (Non-zero)

*	**nonzero() Output:**

*	**First Index Array (Row indices): [0, 0, 1, 2, 2]**
*	Explains which row each non-zero element is in:
*	Both 1 and 3 are in row 0.
*	4 is in row 1.
*	Both 5 and 6 are in row 2.

*	**Second Index Array (Column indices): [0, 2, 1, 0, 1]**
*	Explains which column each non-zero element is in:
*	1 is in column 0, 3 is in column 2.
*	4 is in column 1.
*	5 is in column 0, 6 is in column 1.


Iterating an array can be either performed using the python list style or using the nditer function.

In [65]:
var9 = np.array([[1, 2, 3], [4, 5, 6]])

for i in var9: # outer loop to access row
    print(i) # returns the entire row
print("\n")
for i in var9: # outer loop to access row
    for j in i:  # iterating each element of the row
        print(j) # returns the element value

[1 2 3]
[4 5 6]


1
2
3
4
5
6


In [74]:
# an alternative to the nesting for loop is the nditer function
var10 = np.array([[1, 2, 3], [4, 5, 6]])
for i in np.nditer(var10):
    print(i)

1
2
3
4
5
6


In [76]:
# an alternative to the nesting for loop is the nditer function
var11 = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
for i in np.nditer(var11):
    print(i)

1
2
3
4
5
6
7
8
9


# **Exercise #05:**

*   How can we enumerate a numpy array?



**Solution**

Enumerating a NumPy array means iterating through the array while keeping track of the index positions. It can be used to know both the element and their location within the array.

The `enumerate` function is built into Python and works well with NumPy arrays. When you loop over an array, `enumerate` provides a counter (starting from zero) along with the elements of the array.

...

In [97]:
# Example:
import numpy as np

# Create a NumPy array
array = np.array([10, 20, 30, 40, 50])

# Enumerate through the array
for index, value in enumerate(array):
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: 10
Index: 1, Value: 20
Index: 2, Value: 30
Index: 3, Value: 40
Index: 4, Value: 50


**Enumerating Multi-Dimensional Arrays**

If you're working with multi-dimensional arrays (e.g., matrices), you might need to manage indices for multiple dimensions. One approach is to use np.ndenumerate, which is specially designed for multi-dimensional enumeration:

In [98]:
# Create a 2D NumPy array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Enumerate using np.ndenumerate
for index, value in np.ndenumerate(matrix):
    print(f"Index: {index}, Value: {value}")

Index: (0, 0), Value: 1
Index: (0, 1), Value: 2
Index: (0, 2), Value: 3
Index: (1, 0), Value: 4
Index: (1, 1), Value: 5
Index: (1, 2), Value: 6
Index: (2, 0), Value: 7
Index: (2, 1), Value: 8
Index: (2, 2), Value: 9


**Explanation:**

Basic `enumerate`: Directly generates the index and the value for each item in a one-dimensional array. This is similar to how you'd enumerate a list in Python.

`np.ndenumerate`: Specifically designed for multi-dimensional arrays, providing indices as tuples that reflect the position within the array's dimensions, such as (0, 0) for the first position in a 2D matrix.

---
It has to be noted that, slices share memory with original array. 

In the below example, var12 is created by slicing var11. Notice the change in var11 after modifying var12.

In [ ]:
var11 = np.array([1, 2, 3])

var12 = var11[0:1]

print('before changing:', var11)
var12[0] = 4
print('after changing:', var11)

This leaves us with the question of how the array copy works in numpy

# Array Copy

When you create a new array using the '=' operator, no new copy of the array is created, ie, only a name is created but it refers to the same object.

In [66]:
var13 = np.array([1, 2, 3, 4, 5])

var14 = var13
print('Before modifying', var13)

var14[0] += 1
print('After modifying', var13)

Before modifying [1 2 3 4 5]
After modifying [2 2 3 4 5]


When a view function is used to create a copy of the array, or when the array is sliced, the returned array is only a shallow copy of the original array, ie, an array object is created but the object points to the same data

In [81]:
var15 = np.array([1, 2, 3, 4, 5])

var16 = var15.view()
print('Before modifying (using view)', var15)

var16[0] += 1
print('After modifying (using view)', var15)

var17 = var15[0:3]
print('Before modifying (using slice)', var15)

var17[2] += 1
print('After modifying (using slice)', var15)

Before modifying (using view) [1 2 3 4 5]
After modifying (using view) [2 2 3 4 5]
Before modifying (using slice) [2 2 3 4 5]
After modifying (using slice) [2 2 4 4 5]


To create a deep copy of the array, it is necessary to use the copy method

In [89]:
var18 = np.array([1, 2, 3, 4, 5])

var19 = var18.copy()
print('Before modifying (using copy)', var18)

var19[0] += 1
print('After modifying (using copy)', var18)
print('After modifying (using copy)', var19)

Before modifying (using copy) [1 2 3 4 5]
After modifying (using copy) [1 2 3 4 5]
After modifying (using copy) [2 2 3 4 5]


# Adding new axis

It is also possible to increase the dimensions of a numpy array. **np.newaxis** and **expand_dims** can be used to increase the dimensions of the array. This would be used very handy in building convolutional neural networks where you would need to have uniform channel lengths *(will be used in the later exercises)*.

In [94]:
var20 = np.array([1, 2, 3, 4, 5])
print(var20)
print(var20.shape)
print("\n")
a = var20[np.newaxis, :]  # adding new axis to the first axis
print(a)
print(a.shape)
print("\n")
b = a[np.newaxis, :]  # adding new axis to the first axis
print(b)
print(b.shape)
print("\n")
c = np.expand_dims(var20, axis=1)  # adding new axis to the second axis
print(c)
print(c.shape)
print("\n")
d = np.expand_dims(var20, axis=0)  # adding new axis to the first axis
print(d)
print(d.shape)
print("\n")

[1 2 3 4 5]
(5,)


[[1 2 3 4 5]]
(1, 5)


[[[1 2 3 4 5]]]
(1, 1, 5)


[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


[[1 2 3 4 5]]
(1, 5)




# Broadcasting Rules

Broadcasting deals with how numpy treats arrays with different sizes during arithmetic operations. In general, the smaller arrays are broadcasted into the larger array shapes so that both the arrays are compatible.

Read [basic broadcasting rules](https://numpy.org/doc/stable/user/basics.broadcasting.html) for basic knowledge about broadcasting.
Also read [Array broadcasting](https://numpy.org/doc/stable/user/theory.broadcasting.html#array-broadcasting-in-numpy).


**I do not understand the last example (var20) each row**

In [99]:
var20 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

print(var20)
print('\n')

print(var20 * 2)  # multiplying each element with 2
print('\n')

print(var20 + [1, 0, 1])  # multiplying each row with [1, 0, 1]]

[[1.2 2.3 4. ]
 [1.2 3.4 5.2]
 [0.  1.  1.3]
 [0.  1.  0.2]]


[[ 2.4  4.6  8. ]
 [ 2.4  6.8 10.4]
 [ 0.   2.   2.6]
 [ 0.   2.   0.4]]


[[2.2 2.3 5. ]
 [2.2 3.4 6.2]
 [1.  1.  2.3]
 [1.  1.  1.2]]


**Exercise #06:**

Normalizing values is an important area in any image processing and machine learning problem. In this exercise, we will try to apply normalization at different axis to understand the role of broadcasting.

In [118]:
var21 = np.array([[1.2, 2.3, 4.0],
                  [1.2, 3.4, 5.2],
                  [0.0, 1.0, 1.3],
                  [0.0, 1.0, 2e-1]])

# compute row wise mean
var21_mean_row =   np.mean(var21, axis=1, keepdims=True )                 # code fill up
print('compute All Columns (Across Rows) mean:', var21_mean)

# compute column wise mean
var21_mean_clm = np.mean(var21, axis=0 )                # code fill up
print('compute All Rows (Across Columns) mean:', var21_mean_clm)

# do row wise mean subtraction and column wise mean subtraction
# solution
row_mean_subtracted = var21 - var21_mean_row
print("Row-wise mean subtracted:\n", row_mean_subtracted)


# how do we normalize the entire array using the global mean?
# solution

global_mean = np.mean(var21)
global_std = np.std(var21)

# Normalize using global mean
normalized_array = (var21 - global_mean) / global_std

print("Normalized array using global mean:\n", normalized_array)



compute All Columns (Across Rows) mean: [2.5        3.26666667 0.76666667 0.4       ]
compute All Rows (Across Columns) mean: [0.6   1.925 2.675]
Row-wise mean subtracted:
 [[-1.3        -0.2         1.5       ]
 [-2.06666667  0.13333333  1.93333333]
 [-0.76666667  0.23333333  0.53333333]
 [-0.4         0.6        -0.2       ]]
Normalized array using global mean:
 [[-0.33482623  0.35575287  1.42301148]
 [-0.33482623  1.04633197  2.1763705 ]
 [-1.08818525 -0.46038607 -0.27204631]
 [-1.08818525 -0.46038607 -0.96262542]]


---

*   Can you think of an example of row wise normalization and column wise normalization?



**Solution**

*(Double-click or enter to edit)*

...

**Row-wise Normalization**

*Definition*: Row-wise normalization means adjusting the data across each row so that each element in a row is in relation to the other elements in that row. One common method is to scale the values so that each row sums to 1, or to fit within a fixed range like [0,1].

A dataset where each row represents the daily nutrient intake of a person (e.g., calories, proteins, fats). You might want to normalize each row to sum up to 1 to observe relative proportions for dietary analysis.


In [120]:
import numpy as np

# Example array
data = np.array([[10, 20, 30],
                 [15, 25, 35]])

# Sum each row
row_sums = np.sum(data, axis=1, keepdims=True)

# Row-wise normalization
normalized_rows = data / row_sums
print("Row-wise normalized data:\n", normalized_rows)

Row-wise normalized data:
 [[0.16666667 0.33333333 0.5       ]
 [0.2        0.33333333 0.46666667]]


***Column-wise Normalization***

*Definition*: Column-wise normalization involves adjusting the data such that each element in a column is in relation to the other elements in that column. Often, this could be by standardizing or scaling values within each column to a specific range.

Example:

A classroom where each column is a different exam, and each row represents a student. Column-wise normalization can help manage disparities in grading scales between exams.

In [119]:
# Example array
data = np.array([[40, 60, 80],
                 [50, 70, 90],
                 [60, 80, 100]])

# Find minimum and maximum of each column for min-max scaling
col_min = np.min(data, axis=0)
col_max = np.max(data, axis=0)

# Column-wise normalization to [0, 1] range
normalized_columns = (data - col_min) / (col_max - col_min)
print("Column-wise normalized data:\n", normalized_columns)

Column-wise normalized data:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]




---


**It has to be noted that this is not a complete tutorial covering the complete numpy aspects. This is provided as an introduction to numpy and its ease of use in numerical computation.**